FROM python:3-slim

# Set bash as the default shell
SHELL ["/bin/bash", "-c"]

# Update package list and install basic utilities
RUN apt-get update && apt-get install -y \
    git 

RUN git clone https://github.com/gurkanakdeniz/example-flask-crud.git /App

WORKDIR /App

RUN python3 -m venv venv 
RUN source venv/bin/activate
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

RUN flask db init 
RUN flask db migrate -m "entries table" 
RUN flask db upgrade

# Default command to keep the container running
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]

